In [3]:
import sympy
sympy.Matrix([[1,2,3],[2,3,4]]).rref()

(Matrix([
 [1, 0, -1],
 [0, 1,  2]]),
 (0, 1))

In [5]:
pip install sympy


You should consider upgrading via the 'c:\users\gopikrishnan\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


In [4]:
#reduced row echelon form of matrix rref()
import sympy
sympy.Matrix([[1,2,3],[2,3,4]]).rref()

(Matrix([
 [1, 0, -1],
 [0, 1,  2]]),
 (0, 1))

In [6]:
# Reduced Row echelon
import sympy as sym
A = ([[8,-4,-7,9], [-4,3,6,-4],[-3,-2,-5,-4],[9,-8,-18,7]])

B,i = sym.Matrix(A).rref()
print("\nReduced Row Echelon Form: \n",B)
print("\nPivotal Columns: \n",i)


Reduced Row Echelon Form: 
 Matrix([[1, 0, 0, 1], [0, 1, 0, -2], [0, 0, 1, 1], [0, 0, 0, 0]])

Pivotal Columns: 
 (0, 1, 2)


In [7]:
# Reduced Row Echelon form
import sympy as sym
import numpy as np
A = [[1,-3,4,-2,5,4],[2,-6,9,-1,8,2],[2,-6,9,-1,9,7],[-1,3,-4,2,-5,-4]]
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Column space of A
C = np.array(A)
print("\nColumn Space of A: \n",C[:,i])

Matrix([[1, -3, 0, -14, 0, -37], [0, 0, 1, 3, 0, 4], [0, 0, 0, 0, 1, 5], [0, 0, 0, 0, 0, 0]])
(0, 2, 4)
3

Column Space of A: 
 [[ 1  4  5]
 [ 2  9  8]
 [ 2  9  9]
 [-1 -4 -5]]


In [8]:
# Row Space, Column space
import sympy as sym
import numpy as np
A = [[-2,-5,8,0,-17],[1,3,-5,1,5],[3,11,-19,7,1],[1,7,-13,5,-3]]
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Row Space of A
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])

Matrix([[1, 0, 1, 0, 1], [0, 1, -2, 0, 3], [0, 0, 0, 1, -5], [0, 0, 0, 0, 0]])
(0, 1, 3)
3

Row Space: 
 [[1 0 1 0 1]
 [0 1 -2 0 3]
 [0 0 0 1 -5]]

Column Space: 
 [[-2 -5  0]
 [ 1  3  1]
 [ 3 11  7]
 [ 1  7  5]]


In [9]:
# Row Space, Column space
import sympy as sym
import numpy as np
A = [[-2,-5,8,0,-17],[1,3,-5,1,5],[3,11,-19,7,1],[1,7,-13,5,-3]]
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Row Space of A
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])

Matrix([[1, 0, 1, 0, 1], [0, 1, -2, 0, 3], [0, 0, 0, 1, -5], [0, 0, 0, 0, 0]])
(0, 1, 3)
3

Row Space: 
 [[1 0 1 0 1]
 [0 1 -2 0 3]
 [0 0 0 1 -5]]

Column Space: 
 [[-2 -5  0]
 [ 1  3  1]
 [ 3 11  7]
 [ 1  7  5]]


In [12]:
# Null space and Left null space
from sympy import Matrix
A = [[-2,-5,8,0,-17],[1,3,-5,1,5],[3,11,-19,7,1],[1,7,-13,5,-3]]
A = Matrix(A)
A * A.nullspace()[0]
print("\nNull Space: \n",A.nullspace())

#Transpose of a Matrix
LN = A.T
print("transpose",LN)

#Left Null SPace
LN * LN.nullspace()[0]
print("\nLeft Null Space: \n",LN.nullspace())


Null Space: 
 [Matrix([
[-1],
[ 2],
[ 1],
[ 0],
[ 0]]), Matrix([
[-1],
[-3],
[ 0],
[ 5],
[ 1]])]
transpose Matrix([[-2, 1, 3, 1], [-5, 3, 11, 7], [8, -5, -19, -13], [0, 1, 7, 5], [-17, 5, 1, -3]])

Left Null Space: 
 [Matrix([
[-2],
[-7],
[ 1],
[ 0]])]


In [13]:
# Null space and Left null space
from sympy import Matrix
A = [[-2,-5,8,0,-17],[1,3,-5,1,5],[3,11,-19,7,1],[1,7,-13,5,-3]]
A = Matrix(A)
A * A.nullspace()[0]
print("\nNull Space: \n",A.nullspace())

#Transpose of a Matrix
LN = A.T
print("\nTranspose of A: \n",LN)

#Left Null SPace
LN * LN.nullspace()[0]
print("\nLeft Null Space: \n",LN.nullspace())


Null Space: 
 [Matrix([
[-1],
[ 2],
[ 1],
[ 0],
[ 0]]), Matrix([
[-1],
[-3],
[ 0],
[ 5],
[ 1]])]

Transpose of A: 
 Matrix([[-2, 1, 3, 1], [-5, 3, 11, 7], [8, -5, -19, -13], [0, 1, 7, 5], [-17, 5, 1, -3]])

Left Null Space: 
 [Matrix([
[-2],
[-7],
[ 1],
[ 0]])]


In [14]:
#assignment question 1
import sympy as sym
import numpy as np
A = [[-2,-5,8,0,-17],[1,3,-5,1,5],[3,11,-19,7,1],[1,7,-13,5,-3]]
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Row Space of A
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])

Matrix([[1, 0, 1, 0, 1], [0, 1, -2, 0, 3], [0, 0, 0, 1, -5], [0, 0, 0, 0, 0]])
(0, 1, 3)
3

Row Space: 
 [[1 0 1 0 1]
 [0 1 -2 0 3]
 [0 0 0 1 -5]]

Column Space: 
 [[-2 -5  0]
 [ 1  3  1]
 [ 3 11  7]
 [ 1  7  5]]


In [15]:
#assignment question 2,2
import sympy as sym
import numpy as np
A = [[-2,-1,1,-6,-8],[1,-2,-4,3,-2],[-7,8,10,3,-10],[4,-5,-7,0,4]]
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Row Space of A
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])

Matrix([[1, 0, 0, 0, 4], [0, 1, 0, 7/2, 1], [0, 0, 1, -5/2, 1], [0, 0, 0, 0, 0]])
(0, 1, 2)
3

Row Space: 
 [[1 0 0 0 4]
 [0 1 0 7/2 1]
 [0 0 1 -5/2 1]]

Column Space: 
 [[-2 -1  1]
 [ 1 -2 -4]
 [-7  8 10]
 [ 4 -5 -7]]


In [42]:
#assignment 2 ,1
import sympy as sym
import scipy 
import numpy as np
A = ([[-2,-1,1,-6,-8],[1,-2,-4,3,-2],[-7,8,10,3,-10],[4,-5,-7,0,4]])

B,i = sym.Matrix(A).rref()
c =  np.linalg.matrix_rank(A)


print(c)
print("\nReduced Row Echelon Form: \n",B)
print("\nPivotal Columns: \n",i)


3

Reduced Row Echelon Form: 
 Matrix([[1, 0, 0, 0, 4], [0, 1, 0, 7/2, 1], [0, 0, 1, -5/2, 1], [0, 0, 0, 0, 0]])

Pivotal Columns: 
 (0, 1, 2)


In [18]:
import sympy as sym
import numpy as np
A = ([[1,-2,-4,3,-2],[0,3,9,-12,12],[0,0,0,0,0],[0,0,0,0,0]])

B,i = sym.Matrix(A).rref()
c =  np.linalg.matrix_rank(A)
print("rank",c)
print("\nReduced Row Echelon Form: \n",B)
print("\nPivotal Columns: \n",i)
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])

rank 2

Reduced Row Echelon Form: 
 Matrix([[1, 0, 2, -5, 6], [0, 1, 3, -4, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]])

Pivotal Columns: 
 (0, 1)

Row Space: 
 [[1 0 2 -5 6]
 [0 1 3 -4 4]]

Column Space: 
 [[ 1 -2]
 [ 0  3]
 [ 0  0]
 [ 0  0]]


In [28]:
from sympy import Matrix
import numpy as np
A = ([[1,-4,9,-7],[-1,2,-4,1],[5,-6,10,7]])
A = Matrix(A)
A * A.nullspace()[0]


print("\nNull Space: \n",A.nullspace())
B = ([[1,-4,9,-7],[-1,2,-4,1],[5,-6,10,7]])
c =  np.linalg.matrix_rank(B)
print("rank of a :",c)


Null Space: 
 [Matrix([
[  1],
[5/2],
[  1],
[  0]]), Matrix([
[-5],
[-3],
[ 0],
[ 1]])]
rank of a : 2


In [27]:
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Row Space of A
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])


Null Space: 
 [Matrix([
[  1],
[5/2],
[  1],
[  0]]), Matrix([
[-5],
[-3],
[ 0],
[ 1]])]
rank of a : 2
Matrix([[1, 0, -1, 5], [0, 1, -5/2, 3], [0, 0, 0, 0]])
(0, 1)
2

Row Space: 
 [[1 0 -1 5]
 [0 1 -5/2 3]]

Column Space: 
 [[ 1 -4]
 [-1  2]
 [ 5 -6]]


In [29]:
#assignment 3,1
from sympy import Matrix
import numpy as np
A = ([[1,-4,9,-7],[-1,2,-4,1],[5,-6,10,7]])
A = Matrix(A)
A * A.nullspace()[0]


print("\nNull Space: \n",A.nullspace())
B = ([[1,-4,9,-7],[-1,2,-4,1],[5,-6,10,7]])
c =  np.linalg.matrix_rank(B)
print("rank of a :",c)
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Row Space of A
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])


Null Space: 
 [Matrix([
[  1],
[5/2],
[  1],
[  0]]), Matrix([
[-5],
[-3],
[ 0],
[ 1]])]
rank of a : 2
Matrix([[1, 0, -1, 5], [0, 1, -5/2, 3], [0, 0, 0, 0]])
(0, 1)
2

Row Space: 
 [[1 0 -1 5]
 [0 1 -5/2 3]]

Column Space: 
 [[1 -4]
 [-1 2]
 [5 -6]]


In [30]:
#assignment 3,2
from sympy import Matrix
import numpy as np
A = ([[1,3,4,-1,2],[2,6,6,0,-3],[3,9,3,6,-3],[3,9,0,9,0]])
A = Matrix(A)
A * A.nullspace()[0]


print("\nNull Space: \n",A.nullspace())
B = ([[1,3,4,-1,2],[2,6,6,0,-3],[3,9,3,6,-3],[3,9,0,9,0]])
c =  np.linalg.matrix_rank(B)
print("rank of a :",c)
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Row Space of A
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])


Null Space: 
 [Matrix([
[-3],
[ 1],
[ 0],
[ 0],
[ 0]]), Matrix([
[-3],
[ 0],
[ 1],
[ 1],
[ 0]])]
rank of a : 3
Matrix([[1, 3, 0, 3, 0], [0, 0, 1, -1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0]])
(0, 2, 4)
3

Row Space: 
 [[1 3 0 3 0]
 [0 0 1 -1 0]
 [0 0 0 0 1]]

Column Space: 
 [[1 4 2]
 [2 6 -3]
 [3 3 -3]
 [3 0 0]]


In [36]:
#assignment 3,3
from sympy import Matrix
import numpy as np
A = ([[2,6,-6,6,3,6],[-2,-3,6,-3,0,-6],[4,9,-12,9,3,12],[-2,3,6,3,3,-6]])
A = Matrix(A)
A * A.nullspace()[0]


print("\nNull Space: \n",A.nullspace())
B =  ([[2,6,-6,6,3,6],[-2,-3,6,-3,0,-6],[4,9,-12,9,3,12],[-2,3,6,3,3,-6]])
c =  np.linalg.matrix_rank(B)
print("rank of a :",c)
B,i = sym.Matrix(A).rref()
print(B)
print(i)
print(len(i))

# Row Space of A
R = np.array(B)
print("\nRow Space: \n",R[:len(i),:])

# Column space of A
C = np.array(A)
print("\nColumn Space: \n",C[:,i])



Null Space: 
 [Matrix([
[3],
[0],
[1],
[0],
[0],
[0]]), Matrix([
[ 0],
[-1],
[ 0],
[ 1],
[ 0],
[ 0]]), Matrix([
[-3],
[ 0],
[ 0],
[ 0],
[ 0],
[ 1]])]
rank of a : 3
Matrix([[1, 0, -3, 0, 0, 3], [0, 1, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0]])
(0, 1, 4)
3

Row Space: 
 [[1 0 -3 0 0 3]
 [0 1 0 1 0 0]
 [0 0 0 0 1 0]]

Column Space: 
 [[2 6 3]
 [-2 -3 0]
 [4 9 3]
 [-2 3 3]]


In [31]:
import numpy as np
from numpy import linalg as lialg

A = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])
# Creating an array
a = np.array([[1, 0], [0, 5]])
print("Array is :",a)
# calculating an eigen value
# using eigh() function
c, d = lialg.eig(a)
print("Eigen value is :", c)
print("Eigen vector is :", d)

Array is : [[1 0]
 [0 5]]
Eigen value is : [1. 5.]
Eigen vector is : [[1. 0.]
 [0. 1.]]


In [34]:

    
# Trace of a matrix
# numpy.trace() method
import numpy as np
A = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])

print("\nTrace of A:", np.trace(A))

    
# Determinant
# numpy.linalg.det() method
import numpy as np
A = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])

print("\nDeterminant of A:"
, np.linalg.det(A))



Trace of A: 11

Determinant of A: -306.0


In [2]:
# Determinant
# numpy.linalg.det() method
import numpy as np
A = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])
C = np.linalg.matrix_rank(A)
print("\nDeterminant of A:", np.linalg.det(A))
print("rank of matrix : ",C)


Determinant of A: -306.0
rank of matrix :  3


In [ ]:
# Solving equations Ax = b
# numpy.linalg.solve() method
import numpy as np
A = np.array([[-1,3,2], [1,2,-3],[2,1,-2]])
b = np.array([1, -9,-3])
print(("Solution of linear equations:",
np.linalg.solve(A, b)))