In [14]:
#1 

tuple_ = ("aman","222",777,404.4)

In [2]:
dictionary_ = {"roll no":20,"lastname":'krishnan' ,"firstname":'gopi',"dateofbirth":25051996}
print(dictionary_)

{'roll no': 20, 'lastname': 'krishnan', 'firstname': 'gopi', 'dateofbirth': 25051996}


In [9]:
print(dictionary_.keys())
print(dictionary_.values())

dict_keys(['roll no', 'lastname', 'firstname', 'dateofbirth'])
dict_values([20, 'krishnan', 'gopi', 25051996])


In [7]:
#3 
import numpy as np
a = np.random.randn(2,2)
print(a)

[[ 0.38789262 -0.39534755]
 [-0.41011262  0.08787217]]


In [15]:
#4 
import numpy as np
a=np.random.seed()
print(a)


None


In [12]:
abs(-1234)

1234

In [13]:
#5
import numpy as np
np.random.randint(20,90)

24

In [28]:
#6
import numpy as np
import random
list_ = [11,12,13,14,15]
random.sample([11,12,13,14,15],3)



[11, 13, 15]

In [29]:
np.random.shuffle(list_)
print(list_)

[11, 14, 12, 13, 15]


In [30]:
print(np.random.choice(list_))

13


In [31]:
#7
txt = "the king is dead , long live the king"

fp = open("testfiles.txt", "w")
fp.write(txt)
fp.close()

fp = open("testfiles.txt","r")
print(fp.read())

the king is dead , long live the king


In [33]:
#8

def check(num):
    bool = False
    if num == 0:
        print("element is zero")
    else:
        print("element present")
        
check(9)        

element present


In [34]:
#9
txt = "the king is dead , long live the king"
print(txt)
    
print("first chara:",txt[0])


the king is dead , long live the king
first chara: t


In [35]:
print("character from 3 to 5 :",txt[2:5])

character from 3 to 5 : e k


In [36]:
print("character from 2 :",txt[2:])

character from 2 : e king is dead , long live the king


In [37]:
sp = txt.split()
print(sp)

['the', 'king', 'is', 'dead', ',', 'long', 'live', 'the', 'king']


In [38]:
#10
listt=[1,2,3,4,5]
print("first two elements ",listt[0:2])

first two elements  [1, 2]


In [39]:

#11
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
#12
a= len(arr)
print(a)

2


In [41]:
arr = np.array([[1,2,3],[4,5,6]])
print("second row",arr[1,:])

second row [4 5 6]


In [42]:
c = np.transpose(arr)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [43]:
len_ = np.shape(arr)
print("length of array ",len_[0]*len_[1])

length of array  6


In [44]:
print(arr[0,1],arr[1,1])

2 5


In [48]:
#14 

array = np.array([[1,2,3],[4,5,6]])
print("second row",array[1])


second row [4 5 6]


In [49]:
print(array.T)

[[1 4]
 [2 5]
 [3 6]]


In [50]:
print(array.size)

6


In [51]:
#13
array1 = np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
print(array1.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [54]:
#15

arr = np.array([1,2,3])

for i in range(0,arr.size):
    arr[i]=9
    
arr    

array([9, 9, 9])

In [60]:

import numpy as np
arr = np.array([1,2,3])
               

  
               
print(np.sum(arr))               
               

6


In [62]:
#17 
import numpy as np
a = np.array([77,74,75])
print("product",np.product(a))


product 427350


In [63]:
#18

ar=np.array([2,1,9,2,22,1,1,4,55,6,2,56])
print("mean",np.mean(ar))
print("variance:",np.var(ar))
print("min",np.min(ar))
print("arg min",np.argmin(ar))
print("arg max",np.argmax(ar))
print("standerd deviation",np.std(ar))

mean 13.416666666666666
variance: 386.0763888888889
min 1
arg min 1
arg max 11
standerd deviation 19.648826654253146


In [64]:
#19 

a = np.array([1,1,4,5,5,5,7])
print(np.unique(a))
print(np.sort(a))

[1 4 5 7]
[1 1 4 5 5 5 7]


In [65]:
#20
u=[1,2,3]
v=[0,1,1]
print("dotproduct=",np.dot(u,v))

dotproduct= 5


In [70]:
# 21 
import numpy as np
arr=([[2,-12],[1,-5]])
c,v =np.linalg.eig(arr)  
print(c,v)

[-1. -2.] [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [71]:
#22 correlation


arr1=[11,22,11,31]
arr2=[25,33,31,28]
r=np.corrcoef(arr1,arr2)

In [72]:
print("correlation coefficient:",r)

correlation coefficient: [[1.         0.15997968]
 [0.15997968 1.        ]]
